### ISSUE TITLE
Bad iHome Link transmission

### ISSUE THREAD

**Issue by man-im-unoriginal-af** [luongz/Japan-IPTV#1]
Is there any way to smooth out the iHome links? All players tested (namely VLC, MPC-HC, Potplayer x64, Exoplayer, mpv) returned a glitched transmission. VLC console logs display TS discontinuity.

![image](https://user-images.githubusercontent.com/31392390/156691927-288d0308-2812-4dd1-b1d3-527ba9fb93c5.png)

**Comment by luongz** [comment]
I see . It seems your network problem.

Tested in IPTV app in Android and TiviMate in Android TV , it still run smoothly
I don't have an PC so i will test in my VPS

![Screenshot_20220304-110034.png](https://user-images.githubusercontent.com/76716526/156696959-ede2d81b-71f6-4e49-b8ce-66d2e3d057a8.png)

**Comment by luongz** [comment]
Glitched transmission found in iHome link.
Tested in VLC / PotPlayer.

**Comment by luongz** [comment]
The iHome links run smoothly only in mobile. In PC , it glitched transmission. 

It seems the codec problem. 

I can not controlled the link so i cant fix it.

Thanks for your help!

**Comment by Doraemon-kun** [comment]
I would like to ask since I don't have any issues whatsoever with the NewHome links, no glitches or lags going on: Did the provider fixed the problem or I need to wait before glitches show up?

**Comment by luongz** [comment]
I dont know cause i dont have controlled to the host.
