### ISSUE TITLE
Please Remove MY IPTV Sub (willfonk links) or expect DMCA.

### ISSUE THREAD

**Issue by AstaFatherSatan** [luongz/Japan-IPTV#10]
Please Remove MY IPTV Sub (willfonk links) or expect DMCA.

**Comment by AstaFatherSatan** [comment]
If you do not remove it. I will report you

**Comment by luongz** [comment]
Huh? An user emailed me to add the channel ?

**Comment by luongz** [comment]
> Please Remove MY IPTV Sub (willfonk links) or expect DMCA.

An user has emailed me to added the links
And your list has been public in yamcode , some vk iptv finder?

**Comment by luongz** [comment]
And you are 2nd people to told me remove the link. Wtf?

**Comment by AstaFatherSatan** [comment]
Same person who asked for removal in email. I PM the guy as well. It was on my GitHub before I made it a variable and then it got leaked.

**Comment by AstaFatherSatan** [comment]
I reported the yamcode.

**Comment by AstaFatherSatan** [comment]
Will you remove the links?

**Comment by AstaFatherSatan** [comment]
Would you like a email with the box of the ipv box with the Mac address then?

**Comment by AstaFatherSatan** [comment]
Will you remove the links containing my TV box Mac address I pay monthly fee for before I am forced to get GitHub to make a DMCA request? I don't like being like this but this is starting to become ridiculous to keep my own sub from leaking this way.

**Comment by luongz** [comment]
Done.

Im going to closed this.

**Comment by AstaFatherSatan** [comment]
Thank you

**Comment by AstaFatherSatan** [comment]
One other thing ntd news 24
https://stream01.willfonk.com/live_playlist.m3u8?cid=CS349&r=FHD&ccode=JP&m=d0:20:20:04:35:cc&t=0d6938cb3dcf4b79848bc1753a59d

I apologize but please remove

**Comment by AstaFatherSatan** [comment]
Keep this if it works. This link specifically isn't mine
https://movie.mcas.jp/mcas/smil:wn1.smil/master.m3u8

I appreciate your compliance. I'm thankful
