### ISSUE TITLE
little pair

### ISSUE THREAD

**Issue by LaneSh4d0w** [luongz/Japan-IPTV#11]
Have fun. There might be a bit more channels than what i've found.

http://cdn.us195.jpnettv.live:1935/jptv/janimax_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bsasahi_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/nhkbs1_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bsjapan_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bsnihontv_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bsfuji_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bsasahi_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bstbs_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/bspremium_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/starch2_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/starch3_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/disney_channel/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/Fishing_broadcasting/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/cinefil_wowow_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/igasennmonn_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/gekijjyou/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/Neco/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/movieplus_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/mtv/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/jkids_540/playlist.m3u8
http://cdn.us195.jpnettv.live:1935/jptv/disney_junior/playlist.m3u8

**Comment by luongz** [comment]
Nice find.
But i will wait some days before add it , cause the links source from a
IPTV paid subscription , it will take down the link.

I remember that the link has tokened before
