### ISSUE TITLE
About the problem with NewHome links

### ISSUE THREAD

**Issue by Doraemon-kun** [luongz/Japan-IPTV#5]
I would like to ask since I don't have any issues whatsoever with the NewHome links, no glitches or lags going on: Did the provider fixed the problem or I need to wait before glitches show up?

If there aren't any glitches, you should remove the notice from the file

**Comment by luongz** [comment]
Still have the "glitched" in PC (codec problem??) - tested in PotPlayer in my VPS

Mobile played good the link (idk why) - tested in IPTV app

![IMG_20220320_143647.jpg](https://user-images.githubusercontent.com/76716526/159152961-1363c870-711a-4f30-929f-5c2bb011a6f1.jpg)
![Screenshot_20220320-144107.png](https://user-images.githubusercontent.com/76716526/159153002-b7046fb7-626a-4f61-87f8-82e69815b12d.png)

**Comment by Doraemon-kun** [comment]
I was using mpv on my Windows machine to check out this, but I haven't seen any problem with the video (despite playing for 5min, h264 decoder just complained about some frames were missing at the beginning). So that might be network issue, or from the provider end, since I think anything the phone can play can be played on PC just fine.

This is the error about the frames that I was talking about (it repeated 28 times):
```[ffmpeg/video] h264: sps_id 0 out of range
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: sps_id 0 out of range
[ffmpeg/video] h264: non-existing PPS 0 referenced
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
```

**Comment by luongz** [comment]
> I was using mpv on my Windows machine to check out this, but I haven't seen any problem with the video (despite playing for 5min, h264 decoder just complained about some frames were missing at the beginning). So that might be network issue, or from the provider end, since I think anything the phone can play can be played on PC just fine.
> 
> This is the error about the frames that I was talking about (it repeated 28 times):
> 
> ```
> [ffmpeg/video] h264: non-existing PPS 0 referenced
> [ffmpeg/video] h264: sps_id 0 out of range
> [ffmpeg/video] h264: non-existing PPS 0 referenced
> [ffmpeg/video] h264: decode_slice_header error
> [ffmpeg/video] h264: no frame!
> ```

Okay , thanks for your infomation

I will check the link soon

**Comment by QiangRen2204** [comment]
please update the HLS links, it has an error issue.

**Comment by luongz** [comment]
> please update the HLS links, it has an error issue.

Will do it.
